# DEVELOPMENT ENVIRONMENT OVERRIDES
# ============================================================================

global:
  environment: development

userService:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

productService:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

orderService:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

ingress:
  annotations:
    alb.ingress.kubernetes.io/scheme: internal


postgres:
  persistence:
    enabled: false
